language: r
cache: packages
r:
  - bioc-devel
  - bioc-release
before_install:
  - if [[ "$TRAVIS_R_VERSION_STRING" = 'bioc-devel' ]]; then mkdir ~/.R && echo 'CXX1X=g++ -std=c++0x -g -O2 -fPIC' > ~/.R/Makevars; fi
addons:
  apt:
    packages:
      - libgsl0ldbl
      - libgsl0-dev
