// This file was automatically generated by Kmisc::registerFunctions()

#include <R.h>
#include <Rinternals.h>

#include <R_ext/Rdynload.h>

SEXP motifmatchr_get_thresholds(SEXP matsSEXP, SEXP nuc_freqsSEXP, SEXP pSEXP);
SEXP motifmatchr_get_motif_ix(SEXP matsSEXP, SEXP xSEXP, SEXP nuc_freqsSEXP, SEXP pSEXP, SEXP wSEXP);
SEXP motifmatchr_get_motif_ix_plus(SEXP matsSEXP, SEXP xSEXP, SEXP nuc_freqsSEXP, SEXP pSEXP, SEXP wSEXP);
SEXP motifmatchr_get_motif_positions(SEXP matsSEXP, SEXP xSEXP, SEXP nuc_freqsSEXP, SEXP pSEXP, SEXP wSEXP);

R_CallMethodDef callMethods[]  = {
  {"motifmatchr_get_thresholds", (DL_FUNC) &motifmatchr_get_thresholds, 3},
  {"motifmatchr_get_motif_ix", (DL_FUNC) &motifmatchr_get_motif_ix, 5},
  {"motifmatchr_get_motif_ix_plus", (DL_FUNC) &motifmatchr_get_motif_ix_plus, 5},
  {"motifmatchr_get_motif_positions", (DL_FUNC) &motifmatchr_get_motif_positions, 5},
  {NULL, NULL, 0}
};

void R_init_motifmatchr(DllInfo *info) {
  R_registerRoutines(info, NULL, callMethods, NULL, NULL);
  R_useDynamicSymbols(info, FALSE);
}

